import { Button } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container py-5">
          <div className="row row-cols-1 row-cols-lg-2 align-items-center">
            <div className="col">
              <h1 className='fw-bold'>Write and Read Blogs Here</h1>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate laboriosam sint perspiciatis exercitationem ea nesciunt id ipsum animi, fugiat mollitia odit cupiditate corrupti, minus illum. Est ex modi consectetur natus.</p>
              <Button variant='contained' size='large' className='rounded text-capitalize me-2'>
                Create Blog
              </Button>
              <Button variant='outlined' size='large' className='rounded text-capitalize'>
                Read Blogs
              </Button>
            </div>
            <div className="col">
              <img src="/graphics/girl-reading-newspaper.png" alt="" className='w-100' />
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
